// AUTO-GENERATED by scripts/write-build-info.mjs. Do not edit.
// Placeholder so IDE types resolve before the first build. The real values
// are written by the script during every CI build ("Generate build info").
export interface BuildInfo {
  branch: string; commit: string; commitShort: string;
  dirty: boolean; builtAt: string;
  appVersion: string; androidVersionCode: number | null;
  buildId: string; otaId: string;
}
export const BUILD_INFO: BuildInfo = {
  "branch": "unknown",
  "commit": "unknown",
  "commitShort": "unknown",
  "dirty": false,
  "builtAt": "1970-01-01T00:00:00.000Z",
  "appVersion": "1.0.0",
  "androidVersionCode": null,
  "buildId": "build unknown (unknown)",
  "otaId": "OTA unknown @ 1970-01-01T00:00:00.000Z"
};
