// AUTO-GENERATED by scripts/write-build-info.mjs. Do not edit.
// This committed copy is just a placeholder so IDE types resolve before the
// first build. The real values are written into this file by the script
// during every CI build (workflow step "Generate build info").
export interface BuildInfo {
  branch: string; commit: string; commitShort: string;
  dirty: boolean; builtAt: string;
  appVersion: string; androidVersionCode: number | null;
}
export const BUILD_INFO: BuildInfo = {
  "branch": "unknown",
  "commit": "unknown",
  "commitShort": "unknown",
  "dirty": false,
  "builtAt": "1970-01-01T00:00:00.000Z",
  "appVersion": "1.0.0",
  "androidVersionCode": null
};
