// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character m: concatenates the part arrays.
import { CHARACTER_M_B64_1 } from './character-m-1';
import { CHARACTER_M_B64_2 } from './character-m-2';
import { CHARACTER_M_B64_3 } from './character-m-3';
import { CHARACTER_M_B64_4 } from './character-m-4';
import { CHARACTER_M_B64_5 } from './character-m-5';

export const CHARACTER_M_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_M_B64_1,
  ...CHARACTER_M_B64_2,
  ...CHARACTER_M_B64_3,
  ...CHARACTER_M_B64_4,
  ...CHARACTER_M_B64_5,
];
