// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character f: concatenates the part arrays.
import { CHARACTER_F_B64_1 } from './character-f-1';
import { CHARACTER_F_B64_2 } from './character-f-2';
import { CHARACTER_F_B64_3 } from './character-f-3';
import { CHARACTER_F_B64_4 } from './character-f-4';
import { CHARACTER_F_B64_5 } from './character-f-5';

export const CHARACTER_F_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_F_B64_1,
  ...CHARACTER_F_B64_2,
  ...CHARACTER_F_B64_3,
  ...CHARACTER_F_B64_4,
  ...CHARACTER_F_B64_5,
];
