// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character j: concatenates the part arrays.
import { CHARACTER_J_B64_1 } from './character-j-1';
import { CHARACTER_J_B64_2 } from './character-j-2';
import { CHARACTER_J_B64_3 } from './character-j-3';
import { CHARACTER_J_B64_4 } from './character-j-4';
import { CHARACTER_J_B64_5 } from './character-j-5';
import { CHARACTER_J_B64_6 } from './character-j-6';
import { CHARACTER_J_B64_7 } from './character-j-7';
import { CHARACTER_J_B64_8 } from './character-j-8';
import { CHARACTER_J_B64_9 } from './character-j-9';
import { CHARACTER_J_B64_10 } from './character-j-10';
import { CHARACTER_J_B64_11 } from './character-j-11';
import { CHARACTER_J_B64_12 } from './character-j-12';

export const CHARACTER_J_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_J_B64_1,
  ...CHARACTER_J_B64_2,
  ...CHARACTER_J_B64_3,
  ...CHARACTER_J_B64_4,
  ...CHARACTER_J_B64_5,
  ...CHARACTER_J_B64_6,
  ...CHARACTER_J_B64_7,
  ...CHARACTER_J_B64_8,
  ...CHARACTER_J_B64_9,
  ...CHARACTER_J_B64_10,
  ...CHARACTER_J_B64_11,
  ...CHARACTER_J_B64_12,
];
