// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character k: concatenates the part arrays.
import { CHARACTER_K_B64_1 } from './character-k-1';
import { CHARACTER_K_B64_2 } from './character-k-2';
import { CHARACTER_K_B64_3 } from './character-k-3';
import { CHARACTER_K_B64_4 } from './character-k-4';
import { CHARACTER_K_B64_5 } from './character-k-5';

export const CHARACTER_K_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_K_B64_1,
  ...CHARACTER_K_B64_2,
  ...CHARACTER_K_B64_3,
  ...CHARACTER_K_B64_4,
  ...CHARACTER_K_B64_5,
];
