// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character l: concatenates the part arrays.
import { CHARACTER_L_B64_1 } from './character-l-1';
import { CHARACTER_L_B64_2 } from './character-l-2';
import { CHARACTER_L_B64_3 } from './character-l-3';
import { CHARACTER_L_B64_4 } from './character-l-4';
import { CHARACTER_L_B64_5 } from './character-l-5';
import { CHARACTER_L_B64_6 } from './character-l-6';
import { CHARACTER_L_B64_7 } from './character-l-7';
import { CHARACTER_L_B64_8 } from './character-l-8';
import { CHARACTER_L_B64_9 } from './character-l-9';
import { CHARACTER_L_B64_10 } from './character-l-10';
import { CHARACTER_L_B64_11 } from './character-l-11';
import { CHARACTER_L_B64_12 } from './character-l-12';

export const CHARACTER_L_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_L_B64_1,
  ...CHARACTER_L_B64_2,
  ...CHARACTER_L_B64_3,
  ...CHARACTER_L_B64_4,
  ...CHARACTER_L_B64_5,
  ...CHARACTER_L_B64_6,
  ...CHARACTER_L_B64_7,
  ...CHARACTER_L_B64_8,
  ...CHARACTER_L_B64_9,
  ...CHARACTER_L_B64_10,
  ...CHARACTER_L_B64_11,
  ...CHARACTER_L_B64_12,
];
