// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character g: concatenates the part arrays.
import { CHARACTER_G_B64_1 } from './character-g-1';
import { CHARACTER_G_B64_2 } from './character-g-2';
import { CHARACTER_G_B64_3 } from './character-g-3';
import { CHARACTER_G_B64_4 } from './character-g-4';
import { CHARACTER_G_B64_5 } from './character-g-5';
import { CHARACTER_G_B64_6 } from './character-g-6';
import { CHARACTER_G_B64_7 } from './character-g-7';
import { CHARACTER_G_B64_8 } from './character-g-8';
import { CHARACTER_G_B64_9 } from './character-g-9';
import { CHARACTER_G_B64_10 } from './character-g-10';
import { CHARACTER_G_B64_11 } from './character-g-11';
import { CHARACTER_G_B64_12 } from './character-g-12';

export const CHARACTER_G_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_G_B64_1,
  ...CHARACTER_G_B64_2,
  ...CHARACTER_G_B64_3,
  ...CHARACTER_G_B64_4,
  ...CHARACTER_G_B64_5,
  ...CHARACTER_G_B64_6,
  ...CHARACTER_G_B64_7,
  ...CHARACTER_G_B64_8,
  ...CHARACTER_G_B64_9,
  ...CHARACTER_G_B64_10,
  ...CHARACTER_G_B64_11,
  ...CHARACTER_G_B64_12,
];
