// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character j: concatenates the part arrays.
import { CHARACTER_J_B64_1 } from './character-j-1';
import { CHARACTER_J_B64_2 } from './character-j-2';
import { CHARACTER_J_B64_3 } from './character-j-3';
import { CHARACTER_J_B64_4 } from './character-j-4';
import { CHARACTER_J_B64_5 } from './character-j-5';

export const CHARACTER_J_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_J_B64_1,
  ...CHARACTER_J_B64_2,
  ...CHARACTER_J_B64_3,
  ...CHARACTER_J_B64_4,
  ...CHARACTER_J_B64_5,
];
