// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character d: concatenates the part arrays.
import { CHARACTER_D_B64_1 } from './character-d-1';
import { CHARACTER_D_B64_2 } from './character-d-2';
import { CHARACTER_D_B64_3 } from './character-d-3';
import { CHARACTER_D_B64_4 } from './character-d-4';
import { CHARACTER_D_B64_5 } from './character-d-5';
import { CHARACTER_D_B64_6 } from './character-d-6';
import { CHARACTER_D_B64_7 } from './character-d-7';
import { CHARACTER_D_B64_8 } from './character-d-8';
import { CHARACTER_D_B64_9 } from './character-d-9';
import { CHARACTER_D_B64_10 } from './character-d-10';
import { CHARACTER_D_B64_11 } from './character-d-11';
import { CHARACTER_D_B64_12 } from './character-d-12';

export const CHARACTER_D_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_D_B64_1,
  ...CHARACTER_D_B64_2,
  ...CHARACTER_D_B64_3,
  ...CHARACTER_D_B64_4,
  ...CHARACTER_D_B64_5,
  ...CHARACTER_D_B64_6,
  ...CHARACTER_D_B64_7,
  ...CHARACTER_D_B64_8,
  ...CHARACTER_D_B64_9,
  ...CHARACTER_D_B64_10,
  ...CHARACTER_D_B64_11,
  ...CHARACTER_D_B64_12,
];
