// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character e: concatenates the part arrays.
import { CHARACTER_E_B64_1 } from './character-e-1';
import { CHARACTER_E_B64_2 } from './character-e-2';
import { CHARACTER_E_B64_3 } from './character-e-3';
import { CHARACTER_E_B64_4 } from './character-e-4';
import { CHARACTER_E_B64_5 } from './character-e-5';
import { CHARACTER_E_B64_6 } from './character-e-6';
import { CHARACTER_E_B64_7 } from './character-e-7';
import { CHARACTER_E_B64_8 } from './character-e-8';
import { CHARACTER_E_B64_9 } from './character-e-9';
import { CHARACTER_E_B64_10 } from './character-e-10';
import { CHARACTER_E_B64_11 } from './character-e-11';
import { CHARACTER_E_B64_12 } from './character-e-12';

export const CHARACTER_E_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_E_B64_1,
  ...CHARACTER_E_B64_2,
  ...CHARACTER_E_B64_3,
  ...CHARACTER_E_B64_4,
  ...CHARACTER_E_B64_5,
  ...CHARACTER_E_B64_6,
  ...CHARACTER_E_B64_7,
  ...CHARACTER_E_B64_8,
  ...CHARACTER_E_B64_9,
  ...CHARACTER_E_B64_10,
  ...CHARACTER_E_B64_11,
  ...CHARACTER_E_B64_12,
];
