// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character q: concatenates the part arrays.
import { CHARACTER_Q_B64_1 } from './character-q-1';
import { CHARACTER_Q_B64_2 } from './character-q-2';
import { CHARACTER_Q_B64_3 } from './character-q-3';
import { CHARACTER_Q_B64_4 } from './character-q-4';
import { CHARACTER_Q_B64_5 } from './character-q-5';

export const CHARACTER_Q_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_Q_B64_1,
  ...CHARACTER_Q_B64_2,
  ...CHARACTER_Q_B64_3,
  ...CHARACTER_Q_B64_4,
  ...CHARACTER_Q_B64_5,
];
