// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character i: concatenates the part arrays.
import { CHARACTER_I_B64_1 } from './character-i-1';
import { CHARACTER_I_B64_2 } from './character-i-2';
import { CHARACTER_I_B64_3 } from './character-i-3';
import { CHARACTER_I_B64_4 } from './character-i-4';
import { CHARACTER_I_B64_5 } from './character-i-5';

export const CHARACTER_I_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_I_B64_1,
  ...CHARACTER_I_B64_2,
  ...CHARACTER_I_B64_3,
  ...CHARACTER_I_B64_4,
  ...CHARACTER_I_B64_5,
];
