// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character n: concatenates the part arrays.
import { CHARACTER_N_B64_1 } from './character-n-1';
import { CHARACTER_N_B64_2 } from './character-n-2';
import { CHARACTER_N_B64_3 } from './character-n-3';
import { CHARACTER_N_B64_4 } from './character-n-4';
import { CHARACTER_N_B64_5 } from './character-n-5';

export const CHARACTER_N_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_N_B64_1,
  ...CHARACTER_N_B64_2,
  ...CHARACTER_N_B64_3,
  ...CHARACTER_N_B64_4,
  ...CHARACTER_N_B64_5,
];
