// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character f: concatenates the part arrays.
import { CHARACTER_F_B64_1 } from './character-f-1';
import { CHARACTER_F_B64_2 } from './character-f-2';
import { CHARACTER_F_B64_3 } from './character-f-3';
import { CHARACTER_F_B64_4 } from './character-f-4';
import { CHARACTER_F_B64_5 } from './character-f-5';
import { CHARACTER_F_B64_6 } from './character-f-6';
import { CHARACTER_F_B64_7 } from './character-f-7';
import { CHARACTER_F_B64_8 } from './character-f-8';
import { CHARACTER_F_B64_9 } from './character-f-9';
import { CHARACTER_F_B64_10 } from './character-f-10';
import { CHARACTER_F_B64_11 } from './character-f-11';
import { CHARACTER_F_B64_12 } from './character-f-12';

export const CHARACTER_F_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_F_B64_1,
  ...CHARACTER_F_B64_2,
  ...CHARACTER_F_B64_3,
  ...CHARACTER_F_B64_4,
  ...CHARACTER_F_B64_5,
  ...CHARACTER_F_B64_6,
  ...CHARACTER_F_B64_7,
  ...CHARACTER_F_B64_8,
  ...CHARACTER_F_B64_9,
  ...CHARACTER_F_B64_10,
  ...CHARACTER_F_B64_11,
  ...CHARACTER_F_B64_12,
];
