// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character m: concatenates the part arrays.
import { CHARACTER_M_B64_1 } from './character-m-1';
import { CHARACTER_M_B64_2 } from './character-m-2';
import { CHARACTER_M_B64_3 } from './character-m-3';
import { CHARACTER_M_B64_4 } from './character-m-4';
import { CHARACTER_M_B64_5 } from './character-m-5';
import { CHARACTER_M_B64_6 } from './character-m-6';
import { CHARACTER_M_B64_7 } from './character-m-7';
import { CHARACTER_M_B64_8 } from './character-m-8';
import { CHARACTER_M_B64_9 } from './character-m-9';
import { CHARACTER_M_B64_10 } from './character-m-10';
import { CHARACTER_M_B64_11 } from './character-m-11';
import { CHARACTER_M_B64_12 } from './character-m-12';

export const CHARACTER_M_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_M_B64_1,
  ...CHARACTER_M_B64_2,
  ...CHARACTER_M_B64_3,
  ...CHARACTER_M_B64_4,
  ...CHARACTER_M_B64_5,
  ...CHARACTER_M_B64_6,
  ...CHARACTER_M_B64_7,
  ...CHARACTER_M_B64_8,
  ...CHARACTER_M_B64_9,
  ...CHARACTER_M_B64_10,
  ...CHARACTER_M_B64_11,
  ...CHARACTER_M_B64_12,
];
