// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character p: concatenates the part arrays.
import { CHARACTER_P_B64_1 } from './character-p-1';
import { CHARACTER_P_B64_2 } from './character-p-2';
import { CHARACTER_P_B64_3 } from './character-p-3';
import { CHARACTER_P_B64_4 } from './character-p-4';
import { CHARACTER_P_B64_5 } from './character-p-5';

export const CHARACTER_P_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_P_B64_1,
  ...CHARACTER_P_B64_2,
  ...CHARACTER_P_B64_3,
  ...CHARACTER_P_B64_4,
  ...CHARACTER_P_B64_5,
];
