// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character a: concatenates the part arrays.
import { CHARACTER_A_B64_1 } from './character-a-1';
import { CHARACTER_A_B64_2 } from './character-a-2';
import { CHARACTER_A_B64_3 } from './character-a-3';
import { CHARACTER_A_B64_4 } from './character-a-4';
import { CHARACTER_A_B64_5 } from './character-a-5';

export const CHARACTER_A_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_A_B64_1,
  ...CHARACTER_A_B64_2,
  ...CHARACTER_A_B64_3,
  ...CHARACTER_A_B64_4,
  ...CHARACTER_A_B64_5,
];
