// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character g: concatenates the part arrays.
import { CHARACTER_G_B64_1 } from './character-g-1';
import { CHARACTER_G_B64_2 } from './character-g-2';
import { CHARACTER_G_B64_3 } from './character-g-3';
import { CHARACTER_G_B64_4 } from './character-g-4';
import { CHARACTER_G_B64_5 } from './character-g-5';

export const CHARACTER_G_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_G_B64_1,
  ...CHARACTER_G_B64_2,
  ...CHARACTER_G_B64_3,
  ...CHARACTER_G_B64_4,
  ...CHARACTER_G_B64_5,
];
