// AUTO-GENERATED by scripts/encode-glb-to-ts.mjs — do not edit by hand.
// Aggregator for character e: concatenates the part arrays.
import { CHARACTER_E_B64_1 } from './character-e-1';
import { CHARACTER_E_B64_2 } from './character-e-2';
import { CHARACTER_E_B64_3 } from './character-e-3';
import { CHARACTER_E_B64_4 } from './character-e-4';
import { CHARACTER_E_B64_5 } from './character-e-5';

export const CHARACTER_E_B64_CHUNKS: readonly string[] = [
  ...CHARACTER_E_B64_1,
  ...CHARACTER_E_B64_2,
  ...CHARACTER_E_B64_3,
  ...CHARACTER_E_B64_4,
  ...CHARACTER_E_B64_5,
];
